name: Dot Net Framework (Build)

on:
   push:
     branches:    
      - master

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@master
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.1.1
     
    - name: Restore NuGet Packages
      run: nuget restore log4net.Appender.Loki.sln
    
    - name: Setup-msbuild
      uses: microsoft/setup-msbuild@v1.1.3
    
    - name: Build
      run: msbuild log4net.Appender.Loki.csproj /p:Configuration=Release
